version = 1

[[annotations]]
path = [
    ".gitattributes",
    ".gitignore",
    "LICENSE.md",
    "LICENSES/MIT.txt",
    "REUSE.toml",
    "scripts/**",
]
SPDX-FileCopyrightText = "2026 CrankyAnt"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "DISTRIBUTION.md",
    "LICENSES/LicenseRef-CrankyAnt-Official-Assets.txt",
    "README.md",
    "icons/**",
    "modDesc.xml",
]
SPDX-FileCopyrightText = "2026 CrankyAnt"
SPDX-License-Identifier = "LicenseRef-CrankyAnt-Official-Assets"
